In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns


with open(
    r"C:\Users\hp\OneDrive\Desktop\datacamp\ML practice\WhatsApp Chat with Data Science 2025.txt",
    "r",
    encoding="utf-8"
) as file:
    
    lines = file.readlines()

# Convert into dataframe
df = pd.DataFrame(lines, columns=["Message"])

In [6]:
df.shape

(354, 1)

In [7]:
df.describe()

       Message
count      354
unique     326
top         \n
freq        24

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Message  354 non-null    object
dtypes: object(1)
memory usage: 2.9+ KB

In [9]:
df.isna().sum()

Message    0
dtype: int64

In [10]:
import demoji
def extractor(text):
    emojis = demoji.findall(text)
    return list(emojis.keys())
df["Emojis"] = df["Message"].apply(extractor)
df.head()

                                             Message Emojis
0  12/10/25, 9:42 pm - Messages and calls are end...     []
1  07/10/25, 1:44 pm - ~ Georgios Terzidis create...     []
2  12/10/25, 9:42 pm - You joined using this grou...     []
3  13/10/25, 10:52 am - Ritish Reddy SRH joined u...     []
4  13/10/25, 10:53 am - +91 93264 03634 joined us...     []

In [11]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [12]:
data_without_stopwords = []
for message in df["Message"]:
    words = message.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    data_without_stopwords.append(" ".join(filtered_words))

In [14]:
import nltk
from nltk.tokenize import word_tokenize
tokened_messages = [word_tokenize(message) for message in data_without_stopwords]
tokened_messages[:5]

[['12/10/25',
  ',',
  '9:42',
  'pm',
  '-',
  'Messages',
  'calls',
  'end-to-end',
  'encrypted',
  '.',
  'people',
  'chat',
  'read',
  ',',
  'listen',
  'to',
  ',',
  'share',
  'them',
  '.',
  '*',
  'Learn',
  'more',
  '*'],
 ['07/10/25',
  ',',
  '1:44',
  'pm',
  '-',
  '~',
  'Georgios',
  'Terzidis',
  'created',
  'group',
  '``',
  'Data',
  'Science',
  '2025',
  "''"],
 ['12/10/25',
  ',',
  '9:42',
  'pm',
  '-',
  'joined',
  'using',
  'group',
  "'s",
  'invite',
  'link'],
 ['13/10/25',
  ',',
  '10:52',
  '-',
  'Ritish',
  'Reddy',
  'SRH',
  'joined',
  'using',
  'group',
  'link',
  '.'],
 ['13/10/25',
  ',',
  '10:53',
  '-',
  '+91',
  '93264',
  '03634',
  'joined',
  'using',
  'group',
  'link',
  '.']]